# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
from config import UI_CONFIG

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(800, 800)
         # 获取当前脚本所在目录
        base_dir = os.path.dirname(os.path.abspath(__file__))
        res_dir = os.path.join(base_dir, "res")
        Dialog.setMaximumSize(QtCore.QSize(1952, 2521))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.title_2 = QtWidgets.QLabel(self.frame)
        self.title_2.setGeometry(QtCore.QRect(240, 250, 306, 53))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.title_2.setFont(font)
        self.title_2.setStyleSheet("color: white;")
        self.title_2.setTextFormat(QtCore.Qt.RichText)
        self.title_2.setScaledContents(True)
        self.title_2.setObjectName("title_2")
        self.background = QtWidgets.QLabel(self.frame)
        self.background.setGeometry(QtCore.QRect(0, 0, 800, 800))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap(os.path.join(res_dir, "背景.png")))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.shade = QtWidgets.QLabel(self.frame)
        self.shade.setGeometry(QtCore.QRect(100, 480, 841, 406))
        self.shade.setText("")
        self.shade.setPixmap(QtGui.QPixmap(os.path.join(res_dir, "剪影.png")))
        self.shade.setScaledContents(True)
        self.shade.setObjectName("shade")
        self.name = QtWidgets.QLabel(self.frame)
        self.name.setGeometry(QtCore.QRect(630, 50, 138, 39))
        self.name.setText("")
        self.name.setPixmap(QtGui.QPixmap(os.path.join(res_dir, "校名.png")))
        self.name.setScaledContents(True)
        self.name.setObjectName("name")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(600, 630, 120, 35))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(UI_CONFIG['component_styles']['button'])
        self.pushButton.setObjectName("pushButton")
        self.title = QtWidgets.QLabel(self.frame)
        self.title.setGeometry(QtCore.QRect(110, 180, 570, 53))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("color: white;")
        self.title.setTextFormat(QtCore.Qt.RichText)
        self.title.setScaledContents(True)
        self.title.setObjectName("title")
        self.background.raise_()
        self.title_2.raise_()
        self.shade.raise_()
        self.name.raise_()
        self.pushButton.raise_()
        self.title.raise_()
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_2.setText(_translate("Dialog", "欢迎来到北京大学！"))
        self.pushButton.setText(_translate("Dialog", "开始选课！"))
        self.title.setText(_translate("Dialog", "北京大学计算机方向辅助选课系统"))
